// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qyqs2fQ5c5raZMj3iyJkWM7gDaWHkr0',
    appId: '1:358253272842:web:d1fcc5c0eaa8431c1324f3',
    messagingSenderId: '358253272842',
    projectId: 'videocallapplearning',
    authDomain: 'videocallapplearning.firebaseapp.com',
    storageBucket: 'videocallapplearning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4cpK_BwKXLVPimm8yFW0R1kQUfvqRnoM',
    appId: '1:358253272842:android:f371df29702d2a0d1324f3',
    messagingSenderId: '358253272842',
    projectId: 'videocallapplearning',
    storageBucket: 'videocallapplearning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3NURTOO6JlBHx3Y3zZySOFpA-R89ps8',
    appId: '1:358253272842:ios:375257e2e2657c711324f3',
    messagingSenderId: '358253272842',
    projectId: 'videocallapplearning',
    storageBucket: 'videocallapplearning.firebasestorage.app',
    iosBundleId: 'com.example.videoCallApp',
  );
}
